[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.41"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.41"